import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import type { ReactNode } from "react";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"], // Pilih berat font sesuai kebutuhan
  display: "swap",
});

export const metadata: Metadata = {
  title: "Gemini Chatbot",
  description: "Generated by create next app, supabase, google generative ai and tailwindcss",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body className={poppins.className}>{children}</body>
    </html>
  );
}
